# Generated by Django 5.1.2 on 2024-10-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_reservation_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='phone',
        ),
    ]
