# Generated by Django 5.1.2 on 2024-10-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_reservation_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('starter', 'Entrada'), ('main', 'Prato Principal'), ('dessert', 'Sobremesa'), ('beverage', 'Bebida')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
            ],
        ),
    ]
